### PR TITLE
Debian package creation fixes

### PR DESCRIPTION
**Pull request by Hi-Angel**
This series represents a number of fixes for the non-dkms scst package. 2nd commit fixes a problem where the user-set KVER and KDIR were ignored, which may silently result in invalid package content *(as scst would get build against the running kernel instead)*. 3 and 4 commits fix the problem that `preinst` and `postinst` scripts of the package were using the wrong kernel.

And 1 and 5 commits are just small cleanups; the 5th commit in particular would allow one for example use `ccache` to speed up the build.

The problems being fixed can be seen in particular while building it inside a container.

### CODE REVIEW

**Comment by Hi-Angel** [comment]
As a side note, I really wish `make dpkg` would not run `scripts/clean-source-tree`. This results in the whole tree being rebuilt every time one wants to assemble a package. Though, I'm afraid of doing that change because the package creation stage does a lot of stuff that seems odd to me, like creation of a tar.gz in the `../` directory, so I don't know if removing the call to this script won't break something else.

**Comment by bvanassche** [comment]
Thanks for the patches!

Regarding the unusual aspects of the SCST package build process:
- `scripts/clean-source-tree` is run to make sure that package builds are reproducible.
- The tar.gz file is created in the parent directory because the parent directory is not affected by `scripts/clean-source-tree`.

In case you would have suggestions for further improvements of the package build process, such suggestions are welcome.

**Comment by Hi-Angel** [comment]
Thank you!

> * `scripts/clean-source-tree` is run to make sure that package builds are reproducible.

Would cleaning just the `debian/` directory be enough for that?

> * The tar.gz file is created in the parent directory because the parent directory is not affected by `scripts/clean-source-tree`.

I'm wondering though, what is the purpose of this archive. Is it just so the package building process could find local modifications and abort package creation because of that? If so, this is not really convenient IMO, because local modifications is what one does while developing/debugging.

**Comment by bvanassche** [comment]
> > * `scripts/clean-source-tree` is run to make sure that package builds are reproducible.
> 
> Would cleaning just the `debian/` directory be enough for that?

Unfortunately not. If e.g. a Makefile has been modified, the source code (.c / .h) has to be rebuilt to make sure that the build is reproducible.
 
> > * The tar.gz file is created in the parent directory because the parent directory is not affected by `scripts/clean-source-tree`.
> 
> I'm wondering though, what is the purpose of this archive. Is it just so the package building process could find local modifications and abort package creation because of that? If so, this is not really convenient IMO, because local modifications is what one does while developing/debugging.

Would it help if the source archive would be rebuilt if any source file has been changed, e.g. as follows?
~~~
diff --git a/Makefile b/Makefile
index 36545d500382..15314981129b 100644
--- a/Makefile
+++ b/Makefile
@@ -301,7 +301,9 @@ make-scst-dist =							\
 	tar -c$(1) -f "$${name}-$(3).tar.$(2)" "$${name}-$(3)" &&	\
 	rm -rf "$${name}-$(3)"
 
-scst-dist-gzip:
+scst-dist-gzip: scst-$(VERSION).tar.bz2
+
+scst-$(VERSION).tar.bz2: $(shell scripts/list-source-files)
 	$(call make-scst-dist,j,bz2,$(VERSION),grep -E '^doc/|^fcst/|^iscsi-scst/|^Makefile|^qla2x00t(|_git)/|^scripts/|^scst.spec|^scst/|^scst_local/|^srpt/|^usr/|^scstadmin/')
 
 scst-rpm:
@@ -354,11 +356,13 @@ debian/compat:
 	dpkg-query -W --showformat='$${Version}\n' debhelper 2>/dev/null | \
 	sed 's/\..*//' >$@
 
-../scst_$(VERSION).orig.tar.gz: debian/changelog debian/compat Makefile
+../scst_$(VERSION).orig.tar.gz: debian/changelog debian/compat Makefile	\
+		$(shell scripts/list-source-files)
 	$(call make-scst-dist,z,gz,$(VERSION),cat) &&			\
 	mv "scst-$(VERSION).tar.gz" "$@"
 
-../scst_$(VERSION).orig.tar.xz: debian/changelog debian/compat Makefile
+../scst_$(VERSION).orig.tar.xz: debian/changelog debian/compat Makefile	\
+		$(shell scripts/list-source-files)
 	$(call make-scst-dist,J,xz,$(VERSION),cat) &&			\
 	mv "scst-$(VERSION).tar.xz" "$@"
 
~~~

**Comment by Hi-Angel** [comment]
> Unfortunately not. If e.g. a Makefile has been modified, the source code (.c / .h) has to be rebuilt to make sure that the build is reproducible.

"If the code was modified, it needs to be rebuilt" — yeah, sounds reasonable to me. But doesn't the build-system track the changes? I mean, you can just run `make all`, and it will rebuild everything that was modified in the `all` target. In this regard, removing object files doesn't give any benefit because the end result would be the same. It only unnecessary takes time that a developer has to spend because everything is rebuilt from scratch.

> Would it help if the source archive would be rebuilt if any source file has been changed, e.g. as follows?

Sounds useful! In general, I'm a fan of caches, so if there's a way to do less work and spend less time by memoizing something, that's a ⁺¹ from me ☺

**Comment by bvanassche** [comment]
The patch mentioned in my previous comment has been applied on the master branch.

**Pull request merged**
